### ISSUE TITLE
Only the first spectral match is exported using the export to csv module

### ISSUE THREAD

**Issue by ckbarlow79** [mzmine/mzmine3#1068]
### Basic information

* My operating system and version:  Windows Server 2012/Windows 10
* My MZmine version:  3.3.0

### What happened

I'm exporting a feature list using the export to csv module following running spectral library matching.  In instances where I have multiple spectral matches for a single feature the resulting .csv only contains the first match.   Given that a separate field is provided to specify an identification separator I assume that this is a bug rather than the original intent of the code.

![image](https://user-images.githubusercontent.com/59427858/211182311-d811d2dc-3042-4e72-ac30-60a8d1d01fd8.png)

* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.

The following links to the project I've been using and should illustrate the problem.

https://drive.google.com/drive/folders/1evVkmMkh0rRj8d_zZH839PVCOBf_kR4f?usp=sharing

Kind regards,

Chris

**Comment by robinschmid** [comment]
Will look into this. 
It is actually pretty hard to export all and make it easily human and machine readable.

**Comment by matheus-feralv** [comment]
I'm having the same issue with version 3.3.0, even in the option of "export to csv (Mzmine 2 legacy)", because in Mzmine 2 it's possible to export all ID's.

@robinschmid I believe that have some bug in this function because even selecting the option "export row identity (all ID's)", in .cvs file the row of ID's stay empty.

Mzmine2:
![Untitled](https://user-images.githubusercontent.com/124372019/216627223-b17eb090-2087-4bbd-bef9-aaeede53118d.jpg)

In mzmine 3:
![Untitled2](https://user-images.githubusercontent.com/124372019/216627606-85ee3415-a570-484d-b88a-58b0447e12d1.jpg)

 Hope this can be helpfull to your look in the software.

all the best,

Matheus.

**Comment by robinschmid** [comment]
Need to fix this export all and separate by symbol

**Comment by robinschmid** [comment]
Will be fixed in #1157
