### ISSUE TITLE
GUI + ModularFeature update

### ISSUE THREAD

**Issue by SteffenHeu** [mzmine/mzmine3#107]
Since we want to merge @roman4750 's progress now (**thanks a lot for the hard work!**), we should keep a list of to dos that need to be fixed. Please feel free to add and tick points on this list!

I tried to go through my "standard" procedure as far as i could and noticed a few things already:

### Feature table:

- [x] The height of the feature table rows changes when the plot is loaded
 - set height of row and plot right away
 - remove axis in the plot maybe?
 - maybe render an image once and show the image if we run into performance issues
- [ ] Remove unnecessary logging messages
  - [22:40:36|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Starting processing of task Creating a graphical column for col: Shapes in row: -1
  - [22:40:36|INFO|io.github.mzmine.taskcontrol.impl.WorkerThread]: Processing of task Creating a graphical column for col: Shapes in row: 3 done, status FINISHED
- [ ] Rename Feature Table tabs to "-Feature list name- feature table"
- [x] Make "feature table" tab change data when the feature list selection changes or deactivate/hide the checkbox
- [x] Menu bar in Feature table looks weird
- [x] When opening an aligned feature list table:
 - [23:05:59|WARNING|io.github.mzmine.datamodel.features.types.fx.DataTypeCellValueFactory]: There was no DataTypeMap for the column of DataType class io.github.mzmine.datamodel.features.types.numbers.AsymmetryFactorType and raw file 5471.mzML
- [x] MZmine crashes when a row is selected in an aligned feature table

### Main window:

- [x] Colour feature list names in Feature lists according to raw data file colour
- [x] Move aligned feature lists to their tab

### Other modules

- [x] Chromatogram Deconvolution dialog is all over the place
 - https://imgur.com/Rj5JzD7 (i think i fixed it for ParameterSetupDialogWithScanPreview already)
 - chromatogram selection does not work
- [x] Feature.getRepresentativeScan causes NPE
- [x] When smoothing:
  - [23:01:54|SEVERE|io.github.mzmine.modules.dataprocessing.featdet_smoothing.SmoothingTask]: Smoothing error(java.lang.NullPointerException@io.github.mzmine.modules.dataprocessing.featdet_smoothing.SmoothingTask.run(SmoothingTask.java:199))

-----------------------------
### **To consider:**

- [x] Make "Feature lists" a Tree instead of a list view
- allow grouping by:
 -- module / date created
 -- raw data file
- [ ] Feature lists from older projects are not loaded. Is that intended?

**Comment by roman4750** [comment]
Good idea! I would like to comment some points and add new ones.

- Menu bar in Feature table looks weird
  - I am going to create a tool bar on the right side, simmilarely to the other visualization tabs

- When opening an aligned feature list table:
[23:05:59|WARNING|io.github.mzmine.datamodel.features.types.fx.DataTypeCellValueFactory]: There was no DataTypeMap for the column of DataType class io.github.mzmine.datamodel.features.types.numbers.AsymmetryFactorType and raw file 5471.mzML
  - I think, it's natural, that some features of the aligned feature list are not set before gap filling. So we can either just remove these warning messages or for example fill such features with NaNs and don't show NaNs in the table.  I think, that the first solution is sufficient, because I didn't see any complications due to this.

- Rename Feature Table tabs to "-Feature list name- feature table"
  - I think, we can name all the visualization tabs in a simmilar way(e.g. "-RawDataFile name- 2D Visualizer" for the 2D visualization)

There could be exceptions in data processing modules only beacause the FeatureList is not set for the newly created FeatureListRows and Features. I've fixed it only in a couple of modules.

### To do:
### Modular data model:
- [ ] Should we use DataTypes instead of some local variables(e.g. representiveScanNumber or allMS2FragmentScanNumbers in ModularFeature)?
### Feature table:
- [ ] Implement filtering
- [ ] Paralelize rows creation
- Also there are some issues with FeatureTable parameters. I'll fix them.
### Other modules:
- [ ] Not to create windows instead of tabs, when the number of tabs is equal to 7. We can show a warning for the user to close some opened tabs or somehow squeeze headers and add new ones.

**Comment by SteffenHeu** [comment]
> Not to create windows instead of tabs, when the number of tabs is equal to 7. We can show a warning for the user to close some opened tabs or somehow squeeze headers and add new ones.

That was intended behaviour, we can change that, though. But i thought i'd be good to not show everything in the same window

> When opening an aligned feature list table:
[23:05:59|WARNING|io.github.mzmine.datamodel.features.types.fx.DataTypeCellValueFactory]: There was no DataTypeMap for the column of DataType class io.github.mzmine.datamodel.features.types.numbers.AsymmetryFactorType and raw file 5471.mzML
>    I think, it's natural, that some features of the aligned feature list are not set before gap filling. So we can either just remove these warning messages or for example fill such features with NaNs and don't show NaNs in the table. I think, that the first solution is sufficient, because I didn't see any complications due to this.

Yes, removing the warning is better, because you just might not have a feature in a aligned list

**Comment by tomas-pluskal** [comment]
> > Not to create windows instead of tabs, when the number of tabs is equal to 7. We can show a warning for the user to close some opened tabs or somehow squeeze headers and add new ones.
> 
> That was intended behaviour, we can change that, though. But i thought i'd be good to not show everything in the same window

I agree with Roman here, the app should not open extra windows unless the user wants them. We can make separating tabs easier by adding drag&drop support for moving tabs into external windows, in the same way that Google Chrome does it.

**Comment by SteffenHeu** [comment]
> Should we use DataTypes instead of some local variables(e.g. representiveScanNumber or allMS2FragmentScanNumbers in ModularFeature)?

Btw: allMS2FragmentScanNumbers sounds reasonable because it's optional. However, representiveScanNumber is a necessary value, so it could still be a local var. However, mz and rt are also necessary...

**Comment by robinschmid** [comment]
Closed because of inactivity and most things addressed
