### ISSUE TITLE
Have the wizard giving some very basic IIN adducts and losses by default

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#1186]
**Is your feature request related to a problem? Please describe.**
By default, the wizard does not load any adducts/losses (eventually based on MS polarity) to the IIN step. Having at least 1 or 2 would help.

**Describe the solution you'd like**
Have the wizard loading parts of the adducts / neutral lossses listed by default loaded as default

**Describe alternatives you've considered**
Have a popup saying "We let it empty on purpose because it is up to you to choose them, do not forget doing so, else it will be empty"

**Additional context**
Testing the wizard

**Comment by robinschmid** [comment]
Will be fixed in next release.
The choices were not set but only the selected values.
<img width="427" alt="image" src="https://user-images.githubusercontent.com/10366914/222222311-bc5fc71f-bfb4-4124-a1a4-980d23b9015f.png">

<img width="432" alt="image" src="https://user-images.githubusercontent.com/10366914/222222373-481c4ae9-c71a-4a4e-9ee9-370f79449d93.png">

**Comment by Judyzyw** [comment]
Can mzmine3.4.27  directly identify the adduct form of each feature after GAP-FILLED?
