### ISSUE TITLE
search for specific isotope peak

### ISSUE THREAD

**Issue by RicardoMBorges** [mzmine/mzmine3#1321]
Hello,
I'm trying to search for a specific isotope peak that would appear at 5.031Da from the monoisotopic peak.

I'm trying to do it through the ion identity method and I'm adding a profile for the search.
MS mode: Negative
Maximum charge: 1
Maximum molecules/cluster: 4
Type: Adduct (this I don't know exactly how to change)
Sum formula: ??
Mass difference: 5.031
Charge: -1 (I'm doing - because it is negative mode, but I'm not sure).

Any suggestion might be helpful. Thanks

**Comment by robinschmid** [comment]
metaCorrelate with correlation grouping if the features should come at the same time. Otherwise just disable the correlation filter and increase the retention time tolerance to group everything within x minutes.
![image](https://user-images.githubusercontent.com/10366914/236191092-f738f927-3441-4075-8cc0-4626fcd4062d.png)

Ion identity networking
![image](https://user-images.githubusercontent.com/10366914/236190467-cfd4df3d-660d-41ce-8341-8f8032bf9698.png)
![image](https://user-images.githubusercontent.com/10366914/236190967-ce185653-1ecf-49a7-a92b-813102c3a599.png)

Only issue is that you need to detect 2 adducts at least here. So this is not a complete solution. We would need to add the option to just find the mz difference

**Comment by RicardoMBorges** [comment]
Yes, the features should come at the same time. the mass difference will be 5.031 Da and in negative mode. 
What is the difference between selecting Adducts and Modifications? 
What the Charge in the "Please set the parameters" box means?
What the Sum formula in the "Please set the parameters" box means?

Thanks again

**Comment by RicardoMBorges** [comment]
Hey Robin,
  So the chrom peaks are actually different at about 0.2 mins for the deuterium derivative to the non-deuterium derivative. Maybe this is the reason why IDD is not working here. Any other suggestions?
  Basically, I need to find MS-features that are separated by 5.031 within a threshold of ~0.3 min. My goal is to keep only those in pairs...
Thanks
