### ISSUE TITLE
'missing mass list' error when doing Local minimum resolver

### ISSUE THREAD

**Issue by FunkiiL** [mzmine/mzmine3#1492]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.9.0

### What happened
 Hi all,
After I uploading my .mzML files and doing LC-MS -> ADAP chromatogram builder, I want to do Chromatogram resolving using Local minimum resolver. However, the error message 'missing mass list' keeps appearing, which is shown in the following picture. How to solve this problem? Is it because of my parameter setting?

Thank you very much!

![Screenshot 2023-09-08 152721](https://github.com/mzmine/mzmine3/assets/136693636/8b270721-e620-4363-aad2-acc06230d017)

**Comment by SteffenHeu** [comment]
Hi,

why are you running ADAP on MS2 scans? Anyway, you probably used an rt filter during mass detection and excluded some scans.

**Comment by kirankumarp20** [comment]
> Hi,
> 
> why are you running ADAP on MS2 scans? Anyway, you probably used an rt filter during mass detection and excluded some scans.

![Capture10](https://github.com/mzmine/mzmine3/assets/75622361/0e294d67-610d-4db6-9b3a-7acea7e3f4a2)
 
how to sort this issue ? for ADAP in MS1

**Comment by evepharma** [comment]
Hello Steffen,

I had a similar problem where showed up this little window indicating this warning "missing mass in scan ... and so on..." From the beginning followed all the processes such as Mass detection for MS1, then Mass detection for MS2, then ADAP Chromatogram builder for MS1, then smoothing, and when I applied the Local minimum feature resolver, this message impeded following the operation of the pre-processing data... when you said **retention time filter** during mass detection means that instead of put a short range of time we must put the Auto range in the Mass detection?
 I thought that we could shrink the range of time in order to clean our peaks without affecting the other steps. I would appreciate your comments and insights
Thanks a lot for your time!
