### ISSUE TITLE
Project save/load (modular feature list save/load)

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#150]
Lets collect some challenges and ideas regarding project saving/loading

## Raw data files
- keep raw data files in their original format
- use relative and absolute path
- how to handle missing files?
- what to do after raw data methods change the scan content? (cropping etc)

## MassLists
- save them in binary files?
- can we reuse the memory mapped files? 

## Feature lists (modular)
- each DataType should know how to save and load
- format? csv / json

### how do we safely reference to the correct DataType? 
- consider ManualAnnotationType (extends ModularType) with multiple sub types, e.g., CommentType, FormulaType, ...
- how do we know that a value belongs to a specific data type?
Maybe each data has a unique accession number (from mzML / mzTab-m if available)

**Comment by SteffenHeu** [comment]
> how to handle missing files?
Ideally, the user has the option to package the row files into the mzmine project ("portable project") or keep them in place.

> what to do after raw data methods change the scan content? (cropping etc)
I think we should have a RawDataFileAppliedMethod, storing the whole parameter set, similar to the FeatureListApplied method. Then, files can be reprocessed and we don't have to save a copy. That would save saving mass lists.

> MassLists
> save them in binary files?
> can we reuse the memory mapped files?
I think the memory mapped files are uncompressed, so they will take up a lot of space. Ideally we will be able to just reprocess them. Otherwise, maybe use an mzml export? However, this will also impact the project size a lot.

> Feature lists (modular)
> format? csv / json
I have never used json, so i cannot judge how suited it will be. From what i've heard, it might be easier to store subtypes, especially with regard to annotations, or?
Or can we somehow keep close to an open format here? Maybe mzTabM or so?

Regarding storing the feature data points:
I believe mzml supports storing chromatograms, right? If possible, we should use that.
