### ISSUE TITLE
Charges assigned in exported feature lists (Sirius and GNPS) are different

### ISSUE THREAD

**Issue by jacquelinmeade** [mzmine/mzmine3#1663]
### Basic information

* My operating system and version: 64-bit operating system, Windows 10 Home version 22H2
*My mzMine version: 3.9.0
### What happened

* Please describe what happened and how it differs from what you expected to happen.
After all processing, to include MS1 & MS2 mass detection, chromatogram building, resolving, isotope grouping, feature list alignment, and blank file subtraction, I am exporting the aligned/subtracted feature lists for compound identification in both GNPS and Sirius. 
For this negative ion mode data export that caught my eye, Sucralose is one of my standards that I monitor during the data processing and has a feature # of 1688 assigned in this project. When reviewed in the GNPS export, it has a charge of -6, when viewed in the Sirius export it has a charge of -1, and in the mgf (ADAP) export it has a +1 charge. I do not understand and cannot find where this charge is being assigned and why it would be assigned so differently for the same feature in each mgf exported from the same project.
* Please include all parameter values for the MZmine modules you used. 
I have screenshots of all settings, but if there is a specific setting you'd like to see where this charge may be assigned from, I would be happy to share.
* Please upload screenshots of any errors **and** your log/mzmine.log file.
Not an "error" but I attached the screenshots from the mgf files with the feature 1688 (Sucralose) stated above.
[mgf_screenshots_16Febprocess.docx](https://github.com/mzmine/mzmine3/files/14395286/mgf_screenshots_16Febprocess.docx)

* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
https://drive.google.com/file/d/1JN3BTn26RuimolJRcsBXWzO2p7T_uRKs/view?usp=sharing
I hope the link above works, I'm happy to share another way if it does not.

Thank you for your time and help! 
Jacquelin

**Comment by SteffenHeu** [comment]
Hi, 

that's a good catch. I looked it up and here's what's happening:

The GNPS export uses the charge as detected by the mass spectrometer for the MS2 scan. If the MS fails, the export is also wrong. If no charge was detected by the MS, it defaults to 1 and uses the polarity fo the scan to assign a positive or negative sign.

The Sirius export uses the charge as detected by MZmine by the isotope pattern detection. If no charge stat was determined, we try to use the charge from the ms2 scan, as in the gnps export. Otherwise we default to 1.

The ADAP-GC-EI-GNPS export just uses 1+, as it is the most common charge state found in GC-EI. 

I will adapt the gnps export to use the same procedure as the sirius export.

**Comment by jacquelinmeade** [comment]
Dear SteffenHeu,

I cannot thank you enough for your quick response and consideration of my issue!

All the best,
Jacquelin
