### ISSUE TITLE
Use MSDK raw data model

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#4]
- switch raw data model to MSDK
- remove from MZmine

**Comment by robinschmid** [comment]
I remember that @kaibioinfo changed some parts of the MZmine data model to be more efficient. If I remember correctly the MSDK model is already more efficient - however, do we need to transfer anything?

**Comment by tomas-pluskal** [comment]
The tricky part is when new object instances are created. Because MSDK works with interfaces, and MZmine will need its own implementing classes for those interfaces that are connected to the GUI objects (for example each RawDataFile is an entry in the project tree). But when MSDK creates a new RawDataFile, it needs to know that it should create the object using the class provided by MZmine.

In CDK, they dealt with this issue by using "object builders" (https://github.com/cdk/cdk/blob/master/base/interfaces/src/main/java/org/openscience/cdk/interfaces/IChemObjectBuilder.java). The object builders provide an instance of each class based on the interface. I think we can use the same approach.

**Comment by robinschmid** [comment]
is this really necessary? 
Cant we move everyting of the raw data model to the MSDK and the tree can rely on this?

**Comment by kaibioinfo** [comment]
Hi,

I think I never did changes on the MZmine data model for efficiency reasons. In past I had big performance problems with MZMines mass selection step, but turns out, this was not related to data structures but to a GUI problem which could be easily fixed.

The only problem I had with MZmine data model so far is that it is not easily extendable. If you have a modular plugin based system, you also need a way for plugins to add their own data structures (in particular, add new properties/metadata to the features and feature rows. There is now a String->String HashMap for this purpose, but this is still very limited.

Regarding Factory classes: I think they are quite easy to use in CDK. In fact, you rarely have to create new features or feature rows, anyways. But it should be transparent when to use them. For example, you dont want to create DataPoint instances via Factory, wont you?

**Comment by tomas-pluskal** [comment]
@robinschmid It is necessary for MZmine to use its own objects, because of the binding to the GUI elements (listeners etc.). For example, when you add a Scan to a RawDataFile, the scan has to appear in the project tree. That would not happen automatically if MSDK creates only its own object instances. Handling the GUI elements is actually much easier in JavaFX than in Swing, because we can use ObservableLists. But still we need MZmine-specific objects. I can take care of this part.

**Comment by tomas-pluskal** [comment]
@kaibioinfo Thanks for the feedback. I was actually discussing with @robinschmid just two days ago that we need to make the data model more extendable, with individual modules providing their own data structures and routines for displaying them and saving/loading them.

I wonder why you think it is bad to create DataPoint instances via a factory? I mean, in the MSDK data model we don't use DataPoint anymore, instead we use arrays of primitive types. But in principle I don't see a problem with using factory methods for all objects in the data model.

**Comment by robinschmid** [comment]
Yeah data model was wrong. I think the change was only about the way how scas are read during mass detection.

**Comment by robinschmid** [comment]
As all feature related things are going to stay in mzmine, do we also use factory classes for those?

**Comment by tomas-pluskal** [comment]
We should. It is good for consistency, and also will make it easier to move all the feature-related algorithms into MSDK in the future (but I consider that Stage 2).

**Comment by kaibioinfo** [comment]
> 
> 
>  I wonder why you think it is bad to create DataPoint instances via a factory? I mean, in the MSDK data model we don't use DataPoint anymore, instead we use arrays of primitive types. But in principle I don't see a problem with using factory methods for all objects in the data model.

What I rather mean is that we should only add GUI bindings for stuff that end up in the GUI. If I have so algorithm, its intermediate objects do not necessarily need any GUI binding. So it shouldn't use the same factory as objects that end up in the results. Maybe this is obsolete anyways: when integrating the MSDK, it would make more sense to move all algorithm stuff to MSDK and leave the visualization stuff in mzmine.

**Comment by titodamiani** [comment]
@robinschmid @SteffenHeu 
Hey guys, has this issue been addressed? Can we close it?
