### ISSUE TITLE
ISOTOPE PATTERN FINDER and SIRIUS results visualization

### ISSUE THREAD

**Issue by Giovanni911** [mzmine/mzmine3#613]
Concerning ISOTOPE PATTERN FINDER
When applying the ISOTOPE PATTERN FINDER module with the following parameters (but it always happens) 

![Isotope pattern parameters](https://user-images.githubusercontent.com/72611833/159135591-65bb878c-248e-4aa8-88ee-68084b0a1eea.png)

to some feature lists, I obtain this.

![Isotope pattern](https://user-images.githubusercontent.com/72611833/159135412-21b8ec0a-d648-4235-aec1-4eb11eeae417.png)

Where the number of detected patterns for that feature is reported, but it is impossible to access to which patterns have been found.
How can I know if I found for instance a brominated or chlorinated compound if I have not access to the results? 

Concerning SIRIUS + FINGERID
I run the SIRIUS and FingerID module with an aligned feature list with these parameters

![sirius parameters](https://user-images.githubusercontent.com/72611833/159135648-ebc7220d-8984-49ff-b8f2-f94daa17fdf2.png)

and instead of obtaining wherever possible putative hits, I obtained only for some features some putative molecular formula.

![SIRIUS](https://user-images.githubusercontent.com/72611833/159135400-ccc669bd-6a6b-4945-974d-2912ce6fcce9.png)

Is it running properly this way?
It would be nice if as it is shown in the HEPL section, this tool could give an indication on the putative class and structure, together with the analysis of the isotopic pattern.

Thank you in advance,
Giovanni

**Comment by robinschmid** [comment]
Hey Giovanni,
thanks or testing MZmine and for providing all this feedback. It is best to separate those issues because its easier to track bugs and progress when fixing.
In this case:
### Isotope finder
The isotope finder goes back to the mass lists of the scans to find  a better representation of putative isotope signals. In this step we want to include everything that might be an isotope - we do not score the pattern or filter by intensity. 
The number that you see is the number of signals in the pattern.
You can do two things:
1. right click on a feature and choose show isotope pattern
2. right click and "Search/Predict molecular formula" and select the isotope pattern scoring. You can then select a formula and compare the predicted to the detected isotope pattern. 

### SIRIUS
We actually want to remove the SIRIUS module in the next release. It was a nice addition but those direct connections between tools are hard to maintain. SIRIUS and all related tools have also developed so fast.
The advised way is use the SIRIUS export from MZmine and run SIRIUS individually. In the future, we will enable import of the  SIRIUS, CSI-FingerID, and CANOPUS results.

**Comment by Giovanni911** [comment]
Thank you for the information,
concerning the isotopic pattern even by clicking on show isotopic pattern I am not able to understand which of the two isotopic patterns I was looking for has been found, is it possible to label the feature with the name of the pattern found (for example bromine, chlorine, sulfur, etc.), or to filter them?
Is there in the new version the equivalent of the "adduct search module"? That one properly set was a good tool to find some specific patterns such as bromine or chlorine.

Thank you in advance,
Giovanni
