### ISSUE TITLE
Not detecting masses and not able to run ADAP Chromatogram Builder

### ISSUE THREAD

**Issue by LauraR-1289** [mzmine/mzmine3#668]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3

### What happened

I am having an issue with detecting the masses from my dataset. I uploaded it and did the Mass Detection and it goes fine, but when I do the ADAP Chromatogram Builder, it says:

Error = Scan #1 from (name of the sample) does not have a mass list. Pleas run "Raw data methods" -> "Mass detection". 

I am running 108 files, so I have 108 error messages. I attach the error message just in case. 

I used a TimsTOF Flex (Bruker). I recalibrated the raw data and converted with TIMSconvert (using an Anaconda prompt not the one available through GNPS). 
The Mass detection parameters that I used:
MS1 - Scans (Positive, centroided), Mass detector Noise level (5.0E2, not detecting isotope signals below noise level)
MS2 - Scans (Positive, centroided), Mass detector Noise level (1.0E2, not detecting isotope signals below noise level)

Link to a partial dataset: https://drive.google.com/file/d/1NKbGKn8Dhr7Lqt5nZ4RdTPrb-_Xq90SL/view?usp=sharing

I would very much appreciate if somebody can help me with this bug. 

![Error MZMine3](https://user-images.githubusercontent.com/103540250/163066037-4aa1695a-17a6-4795-91ec-267a586c6009.PNG)

**Comment by xnoonx** [comment]
I've also met that problem. But I found changing the mass detector from 'auto' to other options might help.

**Comment by SteffenHeu** [comment]
Hi Laura,

what was the setting of the "Scan types" parameter? ADAP requires masslists for the frame level.

Furthermore, does timsConvert produce mzML files? If yes, you need to use the mobility scan merging module after mass detection on the mobility scan level to create the accumulated frame spectra for the ADAP builder. 

You can find the step-by-step documentation for the workflow here:
https://mzmine.github.io/mzmine_documentation/workflows/imsworkflow/ion-mobility-data-processing-workflow.html#lc-ms-workflow-recommended

I recommend using the import from the native Bruker data, it also works with recalibration applied (tims&mz). The recalibration must be applied to the raw file though, i don't know if timsconvert does that. If not, using a DA script is a good option.
Or is there a benefit in using timsConvert?

**Comment by LauraR-1289** [comment]
Hello!

xnoonx: I tried with all possibilities and still having the same issue. Thanks for your recommendation. 

Steffen: In the Scan types I left: All scans types. 
Yes, timsConvert produce mzML files, at least with the prompt we are using. I tried to do the Mobility Scan Merging Module with the mzML files but it shows me this error (I send it attached):
"This module is designed for Ion Mobility data only. Cannot process non-ion mobility files. 

![Captura](https://user-images.githubusercontent.com/103540250/163497474-48c933d2-aa4f-4696-aee0-df796b3ead71.PNG)

Also, I tried to import from the native Bruker data (.d) but it does not work. 

So, what I did was recalibrating the raw data using the Bruker software (Data Analysis) and then for converting the data we are using timsConvert to get mzML files because we observed some inconsistencies in the results with the regular Bruker convert platform.

**Comment by Annexhc** [comment]
Hi,
what is the problem when importing native Bruker .d?

**Comment by SteffenHeu** [comment]
Hi Laura, 

i looked into one of the mzml files and there is no mobility dimension in the files, so it's obvious that the mobility scan merging fails.

Did you record the data with TIMS on? Can you upload one file that cannot be imported as the raw .d data?
Furthermore, the problem is, that timsConvert does apparently not correctly report the polarity of the data. If you open the raw data overview, you can see that the polarity is "UNKNOWN". So by only doing mass detection for positive scans, you did not create any mass list. This is an issue that should be reported to the developers of timsConvert.

![grafik](https://user-images.githubusercontent.com/37407705/163595465-328123eb-18ff-41a4-9099-65dba5d77e5b.png)

**Comment by LauraR-1289** [comment]
Hi all!

Annexhc: The problem is that MZmine 3 won't accept the native Bruker .d files. I tried to drag them and nothing happens, also I tried to import them through the Raw Data Import and nothing happens. 

Steffen: Thank you so much for your advise. So, in the Mass Detection I changed the Scan filters settings and set the polarity to any (it was in +). Good news the ADAP Chromatogram builder went through and it doesn't show the error anymore. So the data processing ran perfectly. But... After the processing, I opened the .mgf and .csv files both are empty, there are no masses listed at all (See the image attached). 

It is like it is not detecting any masses even though the data processing doesn't show any error message anymore, which is frustrating. 



![image](https://user-images.githubusercontent.com/103540250/163637327-0dcb89d6-2928-47b0-9fbe-66eaab4623bf.png)

**Comment by SteffenHeu** [comment]
Hello Laura,

please be more specifc to what kind of processing you did and which export you used. It's best tuo upload a standalone project that reproduces the error, so we can look into it and find the issue. We need all parameter settings and module calls, otherwise it is like solving a riddle 😅. From the project we can look into the settings ourselves.

What about the previous question:
> Did you record the data with TIMS on? 
> Can you upload one file that cannot be imported as the raw .d data? 
Which acquisition mode did you use? Auto MS MS, PASEF, prm PASEF, bbCID, dia PASEF...?

I would like to find out what the issue is with the import.
