### ISSUE TITLE
Issue with data import

### ISSUE THREAD

**Issue by eternon** [mzmine/mzmine3#681]
### Basic information

* My operating system: Windows
* My MZmine version:  MZmine 3

### What happened
I tried to import mzXML files converted from Thermo raw data using MSconvert and I have this error message that keeps popping up: 
java.lang.IllegalArgumentException: The m/z values must be sorted in ascending order (AbstractStorableSpectrum.java:76). 

Files were converted using the following parameters:
-  outputformat mzXML
- Binary encoding precision: 32-bit
- Subset: PeackPicking, vendor mslevel=1-2

We loaded our data on the latest version of MZmine 2 without any difficulties.

Thanks for the help!
Eva

**Comment by SteffenHeu** [comment]
Are you using the newest MSConvert version?

We had an issue with the thermo import via the ThermoRawFileParser in the past, and the bug was fixed here: https://github.com/compomics/ThermoRawFileParser/issues/117

I assume MSConvert to use a similar library, so it might be fixed in the newest version. Otherwise, you can use the ThermoRawFileParserGUI here: https://github.com/compomics/ThermoRawFileParserGUI

**Comment by SteffenHeu** [comment]
closed due to inactivity.
