### ISSUE TITLE
Spectral database search not loading

### ISSUE THREAD

**Issue by seanpatcleary** [mzmine/mzmine3#685]
### Basic information

Windows 10
MZmine 3.0.21-beta

### What happened

When I try to load a spectral database in any format, it doesn't actually load.  From what I gather, there are a couple ways to do this, but you first need to load the database before performing spectral database matching.  For clarity, I am using feature list methods -> annotation -> search spectra -> spectral library search.  There's an option in the window to load a spectral library, but doing so doesn't actually load the library.  There's a couple of other ways to do this that I've found (feature list methods -> annotation -> search spectra -> import spectral libraries, raw data methods ->  raw data import -> import spectral libraries), but none of them seem to work.  I have tried a json, msp and mgf file as well.

**Comment by SteffenHeu** [comment]
Hi Sean,

is the spectral library imported to MZmine when you use the spectral library import? Does it appead in the Spectral Libraries tab?

What kind of library are you importing?
Can you upload the library, so we can find out what the issue is?

Best

Steffen

**Comment by GSH-09** [comment]
Was this issue ever solved? I'm experiencing the same/similar thing. I'm on 3.4.27. 
 
I downloaded LC-MS/MS orbitrap and HMDB .JSONs from MoNa. After using LC-MS GridMass to detect features, I clicked on Feature List Methods > Annotation > Search Precursor Mass > Precursor search in spectral libraries. I also tried Annotation > Search Spectra > Spectra Library Search. In both cases, nothing happens afterwards (ie, i don't see any annotations or library search visuals). In the task bar, it does say "processing of task Identify possible precursor... FINISHED".

**Comment by lisakmalins** [comment]
@GSH-09 In MZmine3, the libraries now have to be imported before they are used.

It's explained in the [help document for spectral library search](https://mzmine.github.io/mzmine_documentation/module_docs/id_spectral_library_search/spectral_library_search.html), but I wish the interface was more clear. I feel the UI is misleading because it allows you to select a library file that has not been imported, and then goes through the motions of running the search including the task bar message that you mentioned, but nothing actually happens.

Try using one of the three methods for library import described in the [help document](https://mzmine.github.io/mzmine_documentation/module_docs/id_spectral_library_search/spectral_library_search.html#description) and then run the search and it should work.


@SteffenHeu I believe the only issue here is just confusion over having to import the library before the search can be run -- maybe the spectral library search module could be updated to throw an error if user tries to select a library that has not been imported yet?
