### ISSUE TITLE
ADAP Chrom Resolver Preview

### ISSUE THREAD

**Issue by bmgarcia** [mzmine/mzmine3#686]
* My operating system: Windows 10
* My MZmine version: 3.0.21

In the previous version of MZmine, when using the ADAP Chrom. Resolver Preview as you changed the settings the visuals updated and you could hover over each highlighted peak to see what the SN, intensity, etc. were. 

In this version I am having to change the settings, click to a different peak, and then click back to my peak of interest to see how changing the settings affects my peak picking. I also cannot hover over a peak to view what it's properties are (as described above). 

Is this something in how I am using this tool or are these features no longer present in 3.0?

**Comment by SteffenHeu** [comment]
Hi @bmgarcia, can you please post a step by step description of the preview not updating? I have seen it before, but i was never able to reproduce it consistently to figure out the issue. For me it works as expected in most cases.

As for the peak information: Yes, this feature was unfortunately removed when we recoded the feature resolvers in order to make them more flexible for MZmine 3's ion mobility support.
