### ISSUE TITLE
Export files for FBMN GNPS and SIRIUS empty

### ISSUE THREAD

**Issue by eternon** [mzmine/mzmine3#749]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine 3

### What happened

* I am used to work with MZmine 2 for which I can export files for FBMN jobs and SIRIUS. When I process my data the same way with MZmine 3, the exported files are empty (0 k). 
* LC-HRMS pos mode, ADAP builder, Local minimum, Isotop, Alignment, Feature duplicate, Gap filling. I export to .csv for statistical analysis. That works very well (using the MZmine 2 deprecated) and I try to export the last aligned gap filled list for FBMN and SIRIUS. (I watched the MZmine 3 hands on workshop to see if I could find an answer). 

Many thanks for the help !
Eva

**Comment by SteffenHeu** [comment]
Hey Eva, please make sure the ms2 grouping is enabled in the feature resolving step. Otherwise you can add them afterwards via feature list methods, processing, ms2 grouping.If this issue persists afterwards, please reach out again.Holen Sie sich Outlook für AndroidVon: eternon ***@***.***>Gesendet: Freitag, 24. Juni 2022, 15:31An: mzmine/mzmine3 ***@***.***>Cc: Subscribed ***@***.***>Betreff: [mzmine/mzmine3] Export files for FBMN GNPS and SIRIUS empty (Issue
 #749)
Basic information

My operating system: Windows 10
My MZmine version: MZmine 3

What happened

I am used to work with MZmine 2 for which I can export files for FBMN jobs and SIRIUS. When I process my data the same way with MZmine 3, the exported files are empty (0 k).
LC-HRMS pos mode, ADAP builder, Local minimum, Isotop, Alignment, Feature duplicate, Gap filling. I export to .csv for statistical analysis. That works very well (using the MZmine 2 deprecated) and I try to export the last aligned gap filled list for FBMN and SIRIUS. (I watched the MZmine 3 hands on workshop to see if I could find an answer).

Many thanks for the help !
Eva

**Comment by msheltra** [comment]
I'm having a similar issue using MZmine version 2.53 and Windows 10. When I try to export a feature list FBMN GNPS, I get a quant file, but the actual .mgf file is empty. 
I'm using ADAP chromatogram builder, ADAP deconvolution, isotope peak grouping, duplicate peak filter, join aligner, filtering by rows, and gap filling based using peak finder. 
I'm not seeing an MS2 grouping option in the deconvolution step. Is this the same as either the m/z or RT range for MS2 scan pairing?

**Comment by msheltra** [comment]
So I took your advice and tried doing this in MZmine3, but after going through all the steps-mass detection, chromatogram building, chromatogram resolving, isotope filtering, duplicate peak filtering, alignment, filtering by row, and gap filling, I still had issues. Now when I try to export my gap-filled list via the GNPS - feature based molecular networking option, I'm getting an error saying "Unhandled exception in task Exporting GNPS mgf of MS2 spectra: java.lang.IllegalArgumentException: MS2 scan has no mass list. Run Mass detection on all scans (GnpsFbmnMgfExportTask.java:238). I'm not sure how to generate a mass list when I'm not working with the raw data. Is there anything else I could do to try and get around this issue?
Thanks very much!

**Comment by SteffenHeu** [comment]
This means that you have not run Mass detection MS2 scans. To do that go to raw data methods -> mass detection and set the scan filter to MS level 2. remember MS2 noise levels are usually different from MS1 noise levels.

If you need a place to start when optimising your workflow, you can always start from the wizard.

**Comment by SachinSejuwal** [comment]
I am also facing the same problem. Why it create an empty file when I save my plot (intensity vs m/z) ?
