### ISSUE TITLE
How to use new directions of the MZmine toolbox to spatial metabolomic?

### ISSUE THREAD

**Issue by anani-a-missinou** [mzmine/mzmine3#796]
### Basic information

My operating system: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz 2.21 GHz, 16.0 GB (15.8 GB usable)
My MZmine version: MZmine3.0.21-beta

### What happened

Hi dear developer

I just saw that the mzMine3 version takes mass spectrometry imaging files (*.imzML) as input.
I would like to know the basics of targeted and non-targeted spatial metabolomics data processing workflow currently available on mzMine3 and how to use it.
Until now, I used the software of the manufacturer SCiLS Lab from Brucker, and this evolution of mzMine3 is very interesting for our laboratory.

THANK YOU

**Comment by SteffenHeu** [comment]
Hey,

you can simply import the imzl files just like any other file. The processing uses the same steps as LC-MS processing. Mass detection, feature detection (image builder), deisotoping and further filtering. You should omit the feature resolving step, though.

Depending on the instrument you use (i'm guessing it's a Bruker one since you're using Scils), the RAM of your machine might not be enough. If it's a timsTOF Flex and you acquire with ion mobility enabled, you will definitely need more ram to run a nontarged feature detection.

**Comment by 2AMissinou** [comment]
Hi dear Steffen, 

great think.  I started to explore this on MZmine3.1.0-beta version.

MALDI-MSI was performed using Solarix XR™ 7 Tesla FT-ICR (Bruker Daltonics, Bremen, Germany) mass spectrometer. *.imzML Files fail to load on mzMine3.1.0-beta, due to m/z values that need to be sorted in ascending order.  Below you will find a photo of the error.  

![image](https://user-images.githubusercontent.com/45430190/179986639-1ec7ffc1-7ba0-4f6e-8a98-923bff5661b4.png)

I had already had this problem with MZmine3.0.21-beta, but with mzML files acquired in LC-Orbitrap. It was Robins who solved the problem (see https://github.com/mzmine/mzmine3/issues/722 ). 


thank you

**Comment by robinschmid** [comment]
Sorry for the late response. We had a lot on our todo list. How did you convert

**Comment by robinschmid** [comment]
will be fixed in #1192
