### ISSUE TITLE
Error importing mzML files. m/z must be sorted in ascending order 

### ISSUE THREAD

**Issue by etr08783** [mzmine/mzmine3#817]
* My operating system: Windows 10
* My MZmine version:  MZmine3.0.0 beta

I am trying to import a large dataset of mzML files which have been converted from thermo RAW files using MSconvert. Here are my conversion parameters.

![image](https://user-images.githubusercontent.com/109824419/180517802-7d8d80b2-6eb1-40ac-8f79-d1b2472f7746.png)

When I import the dataset, some files have no issue being imported, but other files throw an error. I just used the mzML import

![image](https://user-images.githubusercontent.com/109824419/180517950-e2dd91bc-438b-4f7f-a969-1d1613ae3989.png)

If I had to guess this might be a compatability issue with the way I converted the data using MSconvert, but I'm not sure. I've tried googling the error but it seems like no one else has run into it. 

[mzmine_log.txt](https://github.com/mzmine/mzmine3/files/9170426/mzmine_log.txt)

I would attach a file that throws the error, but it is above the 25 MB file size.

**Comment by robinschmid** [comment]
Thanks for reporting. I am pretty sure we fixed in in one of the newer releases. Better try mzmine 3.1.0

In general, this is a weird behavior of msconvert or your instrument though, as spectra should be sorted by MZ. Try to also update Ms convert. There should be a second step which is usually there by default, the title maker. 
Make sure to run peak picking first and then title maker. If peak picking is not the first step, it uses a different algorithm. 


Cheers 
Robin

**Comment by etr08783** [comment]
Updated both MSconvert and MZmine and all the problems went away! Thanks

**Comment by robinschmid** [comment]
Great
