### ISSUE TITLE
Scans not sorted in retention time dimension! - exclamation mark in MS data file list

### ISSUE THREAD

**Issue by CUrmann** [mzmine/mzmine3#855]
### Basic information

* My operating system: Win 10 Education 64 bit
* My MZmine version: mzmine 3.2.3

### What happened

Hello,

Many thanks for MZmine3, which I am currently try to use for LC/MS analysis. Unfortunately, there is a problem with the files I use.
Data was generated using a Shimadzu IT TOF and converted using MSconvert to mzml. When the file is imported to MZmine3 an exclamation mark (be aware sign) appears in the MS data file list . Raw data overview works, but clicking on a peak gives the following message: 
Unhandle exeption in task calculating base peak chromatogram of XX in 1 file:java.lan.IllegalArgumentException: Scans not sorted in retention time dimension! Cannot create chromatogram (SimplelonTimeSeries.java:74)
Furthermore, the message appears if I click on a mass in the right window of the raw data overview. No peaks are marked in the left window. 
We tested with older version 3.0.11 beta and there no exclamation mark appeared and there was no error message.
Hopefully, you can help me since I really would appreciate to use Mzmine also with my students at university.

[testproject CU.zip](https://github.com/mzmine/mzmine3/files/9381499/testproject.CU.zip)

**Comment by BioLoggik** [comment]
Operating system: Ubuntu 22.04 (main) and Windows 11
Mzmine: 3.2.3

Hi,
I found a similar problem as @CUrmann. I am currently learning how to use MZmine3 3.2.3, which seems to be a very promising software, but I face lots of tiny bugs. 
On my team, we are working on MS data generated via a Xevo G3 qTOF from Waters, it exports in .raw folders. I am mostly working on Linux distribution (Ubuntu 22.04), and it is not possible to import my waters .raw folders without it crashes after importing around 30-40 scans(I did it also on Windows 11 with the same data and it does not crash). So, I used ProteoWizard to convert my .raw in .mzML and the import now works perfectly in MZmine3 on Ubuntu. 
Then when I was trying to create my chromatograms, following the MZmine3 Documentation instruction, it also raise the same error as for @CUrmann, please see what is written in my .log:
"2022-08-24 11:17:20 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.lang.IllegalArgumentException: Scans not sorted in retention time dimension! Cannot create chromatogram. while processing task Detecting chromatograms in waters_file.mzML"
I did not tried yet with older versions .

In Windows 11, it also raise an error (but different!?) saying that scan #2540 have a tinier retention time than the following scan.

If you need more information to understand my problem please ask. Thank you for your help

**Comment by BioLoggik** [comment]
Update to my precedent message.
It seems when you import raw files from proprietary, there are conversion issues. In my example, it is a qof containing low energy scans, high energy scans, and lock spray scans (a reference compound scan). When it is imported as .raw or (wrongly) converted in mzML files, it keeps the 3 different scan list and lists them as follow: 1, 1, 1, 2, 2, 3, 3, 4, 4, ... rather than 1, 2, 3, 4,... To resolve this problem, I used the GNPS msconvert.bat software (https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion/, a simplified version of proteowizard) and use the 'Double-Click_To-Convert.bat' executable file to create a .mzXML file that contains all my scan in the right increasing order, splitting my low energy scan as MS1 and high energy scans as MS2 (a sort of MS/MS that is suitable for me). And now I can proceed my files with MZmine3.

**Comment by SteffenHeu** [comment]
Hey BioLoggik,

Thanks for the explanation. it would be great to have this in the Mzmine documentation, to have it accessible to all users. Would you want to add it?

You can find it here:

https://mzmine.github.io/mzmine_documentation/index.html
